### ISSUE TITLE
Séparation des environnements

### ISSUE THREAD

**Issue by mendoc** [paxo-phone/PaxOS-8#23]
Bonjour à tous. Déjà bravo pour le travail.
(Je vais rejoindre la communauté.)

Je pense que c'est mieux de séparer les environnements.
C'est bien d'avoir l’émulateur mais ce n'est pas pratique de gérer tout avec les **`#ifdef BUILD_PAXO`** partout.

On peut créer une branche **`emulateur`** qui ne contient que la version du code pour l’émulateur et laisser **`main`** pour le code destiné au microcontrôleur.

**Comment by paxo-rch** [comment]
L'interret des defines est de pouvoir développer a travers l'émulateur, le
téléphone physique en ayant le bon comportement. Plus le code est en
commun, plus l'émulateur sera proche des erreurs sur le paxo.

Le ven. 10 nov. 2023, 03:38, Dimitri ONGOUA ***@***.***> a
écrit :
